# 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'cyberpunk.png', 'gamestart.png',
    'minigame.png', 'no_bullets.png',
    'pigeon_spritesheet.PNG',
    'player_spritesheet.png',
    'player_spritesheet_idle.png',
    'Target.png',
    'neodgm_code.ttf'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    'arrows', 'background', 'explosion', 'sound'
]

