# 메인 파일 이름을 지정하세요.
main_file = 'main.py'

# 데이타 파일들을 지정하세요.
data_files = [
    'football.mp3', 'zombie_pickup.wav', 'pickup.wav',
    'animation_sheet.png', 'ball21x21.png', 'TUK_GROUND_FULL.png',
    'ENCR10B.TTF'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    'zombie'
]

